name: Daily update
on:
  schedule:
    - cron:  '0 16 * * *'
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.name 'Daily update script'
          git config --global user.email 'fxcoudert@users.noreply.github.com'
      - name: Check python version
        run: python3 -V
      - name: Run update script
        env:
          FIGSHARE_TOKEN: ${{ secrets.FIGSHARE_TOKEN }}
          PYTHONUNBUFFERED: 1
        run: ./update.sh
