name: Daily update
on:
  schedule:
    - cron:  '19 * * * *'
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display Python version
        run: python3 -V
      - name: Run update script
        env:
          FIGSHARE_TOKEN: ${{ secrets.FIGSHARE_TOKEN }}
        run: |
          git config --global user.name 'Daily update script'
          git config --global user.email 'fxcoudert@users.noreply.github.com'
          ./update.sh
